Feature/docker compose
SSenpo/DBP_Learn pull request #2
Opened 2022-11-23 15:41 UTC by SSenpo

2022-11-24 00:27 UTC, aleksandr-semenov-dbp requested changes

2022-11-24 00:27 UTC, aleksandr-semenov-dbp commented on TaskManager/docker-compose.yml
> +      - .:app:cached
/app

2022-11-24 14:40 UTC, SSenpo commented on TaskManager/docker-compose.yml
> +      - .:app:cached
> /app

fixed

2022-11-27 00:40 UTC, aleksandr-semenov-dbp approved these changes

2023-01-17 13:04 UTC, merged